name: docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.12
  - pip
  - openff-toolkit
  - openff-qcsubmit==0.57.0
  - pydantic>=2
  - pydantic-settings
  - numpy>=1.16
  - pandas
  - matplotlib
  - numpydoc
  - nbsphinx
  - jupyter_client
  - notebook
  - nbconvert
  - ipykernel
  - autodoc-pydantic
  - myst-parser~=1.0
  - myst-nb
  - pandoc
  - wheel
  - sphinx-autobuild
  - sphinx>=6.2.1,<7
  - pip:
      - readthedocs-sphinx-search >=0.3.2
